version: '3'  # Specify the Docker Compose file format version
services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://username:password@db:5432/chatdb
      - API_URL=http://0.0.0.0:3000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: chatdb
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./src/config/entrypoint.sh:/entrypoint.sh
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

volumes:
  db_data:

